# Generated by Django 3.1.6 on 2021-02-01 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(max_length=254, null=True)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('side_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('website', models.URLField(max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FeatureName', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Memorys',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SpecName', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Spec',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='of Specification!', max_length=254)),
                ('specification_for', models.CharField(default='Motherboard, Graphic Card, etc. ', max_length=254, null=True)),
                ('spec_1', models.CharField(default='Unfortunately we do not have any specification for this product. ', max_length=254)),
                ('spec_2', models.CharField(blank=True, max_length=254)),
                ('spec_3', models.CharField(blank=True, max_length=254)),
                ('spec_4', models.CharField(blank=True, max_length=254)),
                ('spec_5', models.CharField(blank=True, max_length=254)),
                ('spec_6', models.CharField(blank=True, max_length=254)),
                ('spec_7', models.CharField(blank=True, max_length=254)),
                ('spec_8', models.CharField(blank=True, max_length=254)),
                ('spec_9', models.CharField(blank=True, max_length=254)),
                ('spec_10', models.CharField(blank=True, max_length=254)),
                ('spec_11', models.CharField(blank=True, max_length=254)),
                ('spec_12', models.CharField(blank=True, max_length=254)),
                ('spec_13', models.TextField(blank=True)),
                ('spec_14', models.TextField(blank=True)),
                ('spec_15', models.TextField(blank=True)),
                ('spec_10_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_10_names', to='setup.spec')),
                ('spec_11_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_11_names', to='setup.spec')),
                ('spec_12_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_12_names', to='setup.spec')),
                ('spec_13_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_13_names', to='setup.spec')),
                ('spec_14_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_14_names', to='setup.spec')),
                ('spec_15_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_15_names', to='setup.spec')),
                ('spec_1_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_1_names', to='setup.spec')),
                ('spec_2_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_2_names', to='setup.spec')),
                ('spec_3_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_3_names', to='setup.spec')),
                ('spec_4_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_4_names', to='setup.spec')),
                ('spec_5_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_5_names', to='setup.spec')),
                ('spec_6_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_6_names', to='setup.spec')),
                ('spec_7_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_7_names', to='setup.spec')),
                ('spec_8_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_8_names', to='setup.spec')),
                ('spec_9_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec_9_names', to='setup.spec')),
            ],
            options={
                'verbose_name_plural': 'Specification',
            },
        ),
        migrations.CreateModel(
            name='KeyFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ProductCategory Features', max_length=254)),
                ('feature_for', models.CharField(blank=True, default='Motherboard, Graphic Card etc. ', max_length=254)),
                ('feature_1', models.CharField(blank=True, max_length=254)),
                ('feature_2', models.CharField(blank=True, max_length=254)),
                ('feature_3', models.CharField(blank=True, max_length=254)),
                ('feature_4', models.CharField(blank=True, max_length=254)),
                ('feature_5', models.CharField(blank=True, max_length=254)),
                ('feature_1_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_1_names', to='setup.feature')),
                ('feature_2_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_2_names', to='setup.feature')),
                ('feature_3_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_3_names', to='setup.feature')),
                ('feature_4_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_4_names', to='setup.feature')),
                ('feature_5_name', models.ForeignKey(blank=True, default='test1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_5_names', to='setup.feature')),
            ],
            options={
                'verbose_name_plural': 'Key Features',
            },
        ),
    ]
