# Generated by Django 3.1.6 on 2021-02-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_delete_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='spec_1',
            field=models.CharField(default='Unfortunately we do not have any specification for this product.', max_length=254),
        ),
    ]
