# Generated by Django 3.1.6 on 2021-02-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20210202_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name_plural': 'Feature'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name_plural': 'Specifications'},
        ),
    ]
