# Generated by Django 3.1.6 on 2021-02-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20210205_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_1_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_1_names', to='setup.feature'),
        ),
    ]
