# Generated by Django 3.1.6 on 2021-02-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20210205_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyfeatures',
            name='feature_for',
            field=models.CharField(default='ProductName', max_length=254),
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='name',
            field=models.CharField(default='ProductCategoryName', max_length=254),
        ),
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(default='ProductName', max_length=254),
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification_for',
            field=models.CharField(default='ProductCategory', max_length=254, null=True),
        ),
    ]
