# Generated by Django 3.1.6 on 2021-02-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_auto_20210206_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Feature'},
        ),
        migrations.AlterModelOptions(
            name='keyfeatures',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Key Features'},
        ),
        migrations.AlterField(
            model_name='keyfeatures',
            name='name',
            field=models.CharField(default='KeyFeatureName', max_length=254),
        ),
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(default='SpecificationName', max_length=254),
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification_for',
            field=models.CharField(default='ProductName', max_length=254, null=True),
        ),
    ]
