# Generated by Django 3.1.6 on 2021-02-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20210216_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spec',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Spec'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Specifications'},
        ),
    ]
