# Generated by Django 3.1.6 on 2021-02-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20210203_0115'),
        ('products', '0004_auto_20210203_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='setup.category'),
        ),
    ]
